### ISSUE TITLE
Update to Swift 4

### ISSUE THREAD

**Issue by LinusGeffarth** [neobeppe/GTZoomableImageView#4]
Only one little update seems to be necessary to add Swift 4 support:

### `GTZoomableImageView.swift` @104

    #selector(GTZoomableImageView.autoZoom(gesture:))

...requires `@objc` to be added to `autoZoom(gesture:)` @67:

    @objc func autoZoom(gesture: UITapGestureRecognizer) {

That's it!

**Comment by neobeppe** [comment]
Just released 1.1.0 updated to Swift 4.2
